
server:
  port: 18080

spring:
  application:
    name: quelili-cloud-reg-center

eureka:
  instance:
    hostname: 127.0.0.1
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10       # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 20    # 发呆时间，即服务续约到期时间（缺省为90s）
  server:
    enable-self-preservation: false         #关闭自我保护
    eviction-interval-timer-in-ms: 30000    #清理无效节点的时间间隔 30s
  client:
    # 标识是否从 Eureka Server 获取注册信息, 默认是 true. 如果这是一个单节点的 Eureka Server
    # 不需要同步其他节点的数据, 设置为 false
    fetch-registry: false
    # 是否将自己注册到 Eureka Server, 默认是 true. 由于当前应用是单节点的 Eureka Server
    # 需要设置为 false
    register-with-eureka: false
    # 设置 Eureka Server 所在的地址, 查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/